Add `Canada Postal Code` assert
uphold/validator.js-asserts pull request #253
Opened 2024-12-16 15:03 UTC by Megamind51

Add validator for Canada Postal Code.

2024-12-16 18:50 UTC, KevinUphold commented
LGTM.

2024-12-31 12:10 UTC, vitorcoxta requested changes

2024-12-31 12:10 UTC, vitorcoxta commented on src/asserts/canada-postal-code-assert.js
> +const regexp = new RegExp(/^[ABCEGHJKLMNPRSTVXY]\d[A-Z][ -]?\d[A-Z]\d$/);
Let's also accept lowercased letters

2025-01-02 12:29 UTC, vitorcoxta commented
PR title and commit message suggestion:

```
Add Canada zip code assert
```

2025-01-13 14:26 UTC, vitorcoxta reviewed
LGTM to be moved tested in backoffice and then moved to QA.

2025-01-21 11:55 UTC, antoniogferreira approved these changes
LGTM!

https://docs.google.com/spreadsheets/d/1JJz419yrzIvcJ-JkkyGDQhp-L_NJ2kFeZL9mb4bhg4E/edit?gid=0#gid=0

2025-01-22 10:01 UTC, vitorcoxta approved these changes
LGTM!

2025-01-22 10:01 UTC, merged